language: node_js
node_js:
  - '8'

script:
  - npm run lint
  - npm run build

notifications:
  email: false

deploy:
  - provider: script
    on:
      branch: production
    skip_cleanup: true
    script:
      - npx semantic-release
